### ISSUE TITLE
Issues on ex07

### ISSUE THREAD

**Issue by Grazfather** [adityaathalye/clojure-by-example#8]
Hey there,

There are some 'mistakes' in ex07.

1. The imports for ingest and export (json) don't use `:as`
2. io is not mentioned, but needed.

I could fix, but I am not sure if the 'fix' should be to ask the student to fix the imports.

**Comment by adityaathalye** [comment]
Thanks for pointing that out, @Grazfather! 

I've pushed a fix: https://github.com/adityaathalye/clojure-by-example/commit/5be14f3be0c486a1c1d252d1e018e033789649e0

The instructions went stale after the refactoring of Ex06, as of this SHA: de1143c

I hope the material has been of use. I'll be grateful for any other feedback you may have.

**Comment by Grazfather** [comment]
The material has been _very_ useful! I was disappointed there wasn't more after 8 :)

**Comment by adityaathalye** [comment]
> The material has been _very_ useful! I was disappointed there wasn't more after 8 :)

Thank you for letting me know. I've been ruminating about doing s'more about the exercises. A few ideas are brewing. I'd like to give the whole thing a once-over at some point.

Meanwhile, I hope you enjoy playing with the language! If you want to browse around a seriously nontrivial Clojure codebase, give NASA's Common Metadata Repository project a dekko https://github.com/nasa/Common-Metadata-Repository 

:vulcan_salute:
